### ISSUE TITLE
Saída não vai para o log...

### ISSUE THREAD

**Issue by joismar** [lcc/javadoc-parser#1]
No primeiro RUN obtive o seguinte erro:

```log
Traceback (most recent call last):
  File "parser.py", line 279, in <module>
    main()
  File "parser.py", line 275, in main
    res = filter_by_documentation(my_files)
  File "parser.py", line 240, in filter_by_documentation
    method = parsed_method(method, anchor, file_)
  File "parser.py", line 40, in __init__
    self.name = method.find(self.METHOD_NAME_TAG).get_text(' ', strip=True)
AttributeError: 'NoneType' object has no attribute 'get_text'
```

Então adicionei a seguinte linha no __init__ pra verificar se a tag ta com o valor de get_text nulo:

```python
def __init__(self, method, anchor, file_path):
	if method.find(self.METHOD_NAME_TAG) != None: # se for nulo faz nada
		self.name = method.find(self.METHOD_NAME_TAG).get_text(' ', strip=True)
		self.set_description(method)
		self.set_anchor(anchor, file_path)
```

Dai rodou normalmente e meu parser termina dessa forma...

```log
...
Examining file 914 of 929
doStartTag--
createValidator--
file://C:\Users\joism\Desktop\JAVADOC\myfaces-api-2.3.4-javadoc\javax\faces\webapp\ValidatorELTag.html#doStartTag--
file://C:\Users\joism\Desktop\JAVADOC\myfaces-api-2.3.4-javadoc\javax\faces\webapp\ValidatorELTag.html#createValidator--
Examining file 915 of 929
setValidatorId-java.lang.String-
doStartTag--
release--
createValidator--
setBinding-java.lang.String-
file://C:\Users\joism\Desktop\JAVADOC\myfaces-api-2.3.4-javadoc\javax\faces\webapp\ValidatorTag.html#setValidatorId-java.lang.String-
file://C:\Users\joism\Desktop\JAVADOC\myfaces-api-2.3.4-javadoc\javax\faces\webapp\ValidatorTag.html#doStartTag--
file://C:\Users\joism\Desktop\JAVADOC\myfaces-api-2.3.4-javadoc\javax\faces\webapp\ValidatorTag.html#release--
file://C:\Users\joism\Desktop\JAVADOC\myfaces-api-2.3.4-javadoc\javax\faces\webapp\ValidatorTag.html#createValidator--
file://C:\Users\joism\Desktop\JAVADOC\myfaces-api-2.3.4-javadoc\javax\faces\webapp\ValidatorTag.html#setBinding-java.lang.String-
Examining file 916 of 929
Examining file 917 of 929
Examining file 918 of 929
Examining file 919 of 929
Examining file 920 of 929
Examining file 921 of 929
Examining file 922 of 929
Examining file 923 of 929
Examining file 924 of 929
Examining file 925 of 929
Examining file 926 of 929
Examining file 927 of 929
Examining file 928 of 929
```
Porém o log sai vazio e não consigo entender essas saidas printadas. Ainda não consegui descobrir onde que ta o problema.

**Comment by lcc** [comment]
Opa, tudo certo?

Olha, não estou com muito tempo pra olhar os ins-outs do script. Ele não
está perfeito, vai deixar algumas coias passarem,  e não está usando filtro
de KEYWORDS (estou sem tempo para implementar). Acabei de dar push na
branch "basic-parse" . Edite o arquivo run.py com o PROJECT_PATH e LOG_PATH
do seu projeto.  Isso gerará um arquivo de log com todas as classes (sem
filtro algum).

P.S: Se quiser implementar o filtro de keywords, deveria ser no arquivo
parsed_class, verificando se a descrição de cada método possui aquelas
palavras chave. Algo do gênero "if keyword in method.description: log();"

Att,
Lucas Cabral

Em seg, 16 de set de 2019 às 22:15, Joismar Braga <notifications@github.com>
escreveu:
